import Head from 'next/head';
import Image from 'next/image';
import { useState, useEffect } from 'react';
import { FaHeart } from 'react-icons/fa';
import { FiHeart } from 'react-icons/fi';
import NavBar from '../components/NavBar';
import SpaceCard from '../components/SpaceCard';
import styles from '../styles/Home.module.css';

export default function Home ({ data }) {
	const [
		pictures,
		setPictures
	] = useState(data);

	const [
		spaceFavs,
		setSpaceFavs
	] = useState([]);

	const [
		likes,
		setLikes
	] = useState(false);

	const [
		icon,
		setIcon
	] = useState(false);

	useEffect(() => {
		const favs = JSON.parse(localStorage.getItem('spacetagram-favs'));
		if (favs === null) {
			setSpaceFavs([]);
		}
		else {
			setSpaceFavs(favs);
		}
	}, []);

	const saveToLocalStorage = (items) => {
		localStorage.setItem('spacetagram-favs', JSON.stringify(items));
	};

	const addFav = (spaceItem) => {
		const newFav = [
			...spaceFavs,
			spaceItem
		];
		setSpaceFavs(newFav);
		saveToLocalStorage(newFav);
		setIcon(!icon);
	};

	const removeFav = (title, date) => {
		const newFav = spaceFavs.filter((f) => f.title !== title && f.date !== date);

		setSpaceFavs(newFav);
		saveToLocalStorage(newFav);
		setIcon(!icon);
	};

	const showLikes = () => {
		setLikes(!likes);
	};

	const match = spaceFavs.filter((e) => pictures.some((e2) => e2.title === e.title && e2.date === e.date));

	return (
		<div>
			<NavBar spaceFavs={spaceFavs} showLikes={showLikes} likes={likes} />
			<div className={styles.container}>
				<Head>
					<title>Spacestagram App</title>
					<meta name="description" content="Generated by create next app" />
					<link rel="icon" href="/favicon.ico" />
				</Head>

				<main className={styles.main}>
					{likes ? (
						<h1 className={styles.title}>
							<span>Likes</span>
						</h1>
					) : (
						<h1 className={styles.title}>
							Welcome to <span>Spacestagram!</span>
						</h1>
					)}

					{!likes && (
						<p className={styles.description}>
							Like and unlike pictures of <strong>SPACE</strong> provided by{' '}
							<a href="https://api.nasa.gov/#apod">NASA's API!</a>
						</p>
					)}

					{likes ? (
						<div className={styles.grid}>
							{spaceFavs.map((pic, idx) => (
								<SpaceCard
									pic={pic}
									addFav={addFav}
									removeFav={removeFav}
									key={`${pic.date}-${idx}`}
									url={pic.url}
									media_type={pic.media_type}
									thumbnail_url={pic.thumbnail_url}
									title={pic.title}
									date={pic.date}
									explanation={pic.explanation}
									icon={icon}
								/>
							))}
						</div>
					) : (
						<div className={styles.grid}>
							{pictures.map((pic, idx) => (
								<SpaceCard
									pic={pic}
									addFav={addFav}
									removeFav={removeFav}
									key={`${pic.date}-${idx}`}
									url={pic.url}
									media_type={pic.media_type}
									thumbnail_url={pic.thumbnail_url}
									title={pic.title}
									date={pic.date}
									explanation={pic.explanation}
									icon={icon}
								/>
							))}
						</div>
					)}
				</main>

				<footer className={styles.footer}>
					<a
						href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
						target="_blank"
						rel="noopener noreferrer"
					>
						Powered by{' '}
						<span className={styles.logo}>
							<Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
						</span>
					</a>
				</footer>
			</div>
		</div>
	);
}

export async function getServerSideProps () {
	try {
		const res = await fetch(
			'https://api.nasa.gov/planetary/apod?api_key=bwQwkRMCuNfINAZVluomxyUm0cTSPSKdIAbZwtoA&count=9&thumbs=true'
		);
		const data = await res.json();
		return {
			props : { data }
		};
	} catch (e) {
		console.log(e);
	}
}
