import Head from 'next/head';
import { useState, useEffect } from 'react';
import { FiHeart } from 'react-icons/fi';
import SpaceList from '../components/SpaceList';
import styles from '../styles/Home.module.css';

export default function Home ({ data }) {
	const [
		pictures,
		setPictures
	] = useState(data);

	const [
		spaceFavs,
		setSpaceFavs
	] = useState([]);

	const [
		loading,
		setLoading
	] = useState(false);

	useEffect(() => {
		const favs = JSON.parse(localStorage.getItem('spacetagram-favs'));
		if (favs === null) {
			setSpaceFavs([]);
		}
		else {
			setSpaceFavs(favs);
		}
	}, []);

	const saveToLocalStorage = (items) => {
		localStorage.setItem('spacetagram-favs', JSON.stringify(items));
	};

	const addFav = (item) => {
		if (spaceFavs.some((el) => el.title === item.title)) {
			return;
		}
		else {
			const newKey = { liked: true };
			item = { ...item, ...newKey };
			const newFav = [
				...spaceFavs,
				item
			];
			const objIdx = pictures.findIndex((obj) => obj.title == item.title);
			const updatedObj = { ...pictures[objIdx], liked: true };
			const newPicFav = [
				...pictures.slice(0, objIdx),
				updatedObj,
				...pictures.slice(objIdx + 1)
			];
			setSpaceFavs(newFav);
			saveToLocalStorage(newFav);
			setPictures(newPicFav);
		}
	};

	const removeFav = (item) => {
		const newFav = spaceFavs.filter((f) => f.title !== item.title && f.date !== item.date);
		const objIdx = pictures.findIndex((obj) => obj.title == item.title);
		const updatedObj = { ...pictures[objIdx], liked: false };
		const newPicFav = [
			...pictures.slice(0, objIdx),
			updatedObj,
			...pictures.slice(objIdx + 1)
		];

		setSpaceFavs(newFav);
		saveToLocalStorage(newFav);
		setPictures(newPicFav);
	};

	const getMoreItems = async () => {
		try {
			setLoading(!loading);
			const res = await fetch(
				'https://api.nasa.gov/planetary/apod?api_key=bwQwkRMCuNfINAZVluomxyUm0cTSPSKdIAbZwtoA&count=9&thumbs=true'
			);
			const data = await res.json();
			const newItems = pictures.concat(data);
			setPictures(newItems);
			setLoading(false);
		} catch (e) {
			console.log(e);
		}
	};

	return (
		<div>
			<div className={styles.container}>
				<Head>
					<title>Spacestagram App</title>
					<meta name="description" content="Generated by create next app" />
					<link rel="icon" href="/favicon.ico" />
				</Head>

				<main className={styles.main}>
					<h1 className={styles.title}>
						Welcome to <span>Spacestagram!</span>
					</h1>

					<p className={styles.description}>
						Like and unlike pictures of <strong>SPACE</strong> provided by the {' '}
						<a href="https://api.nasa.gov/#apod">NASA's API!</a>
					</p>

					<div className={styles.grid}>
						<SpaceList context={pictures} handleAdd={addFav} handleRemove={removeFav} icon={<FiHeart />} />
					</div>

					<button className={`${styles.likeBtn} ${styles.moreBtn}`} onClick={() => getMoreItems()}>
						{loading ? (
							<span>
								Loading...<div />
							</span>
						) : (
							'More'
						)}
					</button>
				</main>
			</div>
		</div>
	);
}

export async function getStaticProps () {
	try {
		const res = await fetch(
			'https://api.nasa.gov/planetary/apod?api_key=bwQwkRMCuNfINAZVluomxyUm0cTSPSKdIAbZwtoA&count=9&thumbs=true'
		);
		const data = await res.json();
		return {
			props : { data }
		};
	} catch (e) {
		console.log(e);
	}
}
